version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.4
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
